### ISSUE TITLE
feature：Github图床

### ISSUE THREAD

**Issue by hackycy** [hackycy/flutter-picgo#1]

**Comment by Molunerfinn** [comment]
有兴趣可以加入 [PicGo organization](https://github.com/PicGo) 呀

**Comment by hackycy** [comment]
> 有兴趣可以加入 [PicGo organization](https://github.com/PicGo) 呀

有兴趣呀

**Comment by hackycy** [comment]
> 有兴趣可以加入 [PicGo organization](https://github.com/PicGo) 呀

有兴趣呀

**Comment by hackycy** [comment]
@Molunerfinn 
有兴趣呀

**Comment by upupming** [comment]
这个手动填写配置是不是有点麻烦，可不可以扫描二维码，类似于 ssr 和 v2ray 那种，感觉可能会比较方便~

**Comment by hackycy** [comment]
@upupming 

二维码方式操作如何操作？虽然我也觉得麻烦，但是目前是跟PicGo的操作方式，就是换做在手机上比较麻烦，Github配置的填写也不少呀

**Comment by upupming** [comment]
刚刚测试了一下，会404，是不是有点小问题呢

![Screenshot_20200625-132845](https://user-images.githubusercontent.com/24741764/85660278-04f42b00-b6e8-11ea-889c-085594fb5d0b.png)

**Comment by upupming** [comment]
@hackycy 

> @upupming
> 
> > 这个手动填写配置是不是有点麻烦，可不可以扫描二维码，类似于 ssr 和 v2ray 那种，感觉可能会比较方便~
> 
> 二维码方式操作如何操作？虽然我也觉得麻烦，但是目前是跟PicGo的操作方式，就是换做在手机上比较麻烦，Github配置的填写也不少呀

PicGo的配置就是 JSON 文件，可以使用类似Chrome插件[Quick QR](https://chrome.google.com/webstore/detail/quick-qr-code-generator/afpbjjgbdimpioenaedcjgkaigggcdpp) 来把 JSON 转成二维码，客户端扫描一下就好~

**Comment by hackycy** [comment]
> 刚刚测试了一下，会404，是不是有点小问题呢
> 
> ![image](https://user-images.githubusercontent.com/24741764/85660757-92d01600-b6e8-11ea-8d19-d4a3992f5d9d.png)

@upupming 

可以尝试在Github配置下右上角有一个测试连接，测试连接通过可以访问仓库内容下上传不会有问题的。但是手机访问github api经常会出现api无法访问。这一点暂时没有办法解决。目前我都是需要手机切换一下网络。而且如果不配合自定义域名+ github page情况下图片是无法加载的。

**Comment by upupming** [comment]
> > 刚刚测试了一下，会404，是不是有点小问题呢
> > ![image](https://user-images.githubusercontent.com/24741764/85660757-92d01600-b6e8-11ea-8d19-d4a3992f5d9d.png)
> 
> @upupming
> 
> 可以尝试在Github配置下右上角有一个测试连接，测试连接通过可以访问仓库内容下上传不会有问题的。但是手机访问github api经常会出现api无法访问。这一点暂时没有办法解决。目前我都是需要手机切换一下网络。而且如果不配合自定义域名+ github page情况下图片是无法加载的。

抱歉，刚刚是我自己配错了😅，现在没有问题了应该
